version: "2"

run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: '(.+)_test\.go'
        linters:
          - gosec
          - errcheck
      - linters:
          - errcheck
        text: "is not checked"
      - path: internal/config/email_template_files\.go
        text: "G304:"
        linters:
          - gosec
      - linters:
          - gosec
        text: "G101:|G104:"
      - linters:
          - staticcheck
        text: "SA1019:|QF1003:|QF1001:|ST1018:"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
