# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: jellygate
# No before hooks - frontend build is done by the Dockerfile explicitly
builds:
  - id: notray-e2ee
    dir: ./
    env:
      - CGO_ENABLED=1
      - CC={{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}-linux-gnu{{ if eq .Arch "arm" }}eabihf{{ end }}-gcc
      - CXX={{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}-linux-gnu{{ if eq .Arch "arm" }}eabihf{{ end }}-gcc
      - PKG_CONFIG_PATH=/usr/lib/{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else }}{{ .Arch }}{{ end }}-linux-gnu{{ if eq .Arch "arm" }}eabihf{{ end }}/pkgconfig:$PKG_CONFIG_PATH
      - GOARM={{ if eq .Arch "arm" }}7{{ end }}
    flags:
      - -tags=e2ee,goolm,{{ .Env.JFA_GO_TAG }}
    ldflags:
      - -X main.version={{.Env.JFA_GO_VERSION}} -X main.commit={{.ShortCommit}} -X main.updater={{.Env.JFA_GO_UPDATER}} {{.Env.JFA_GO_STRIP}} -X main.cssVersion={{.Env.JFA_GO_CSS_VERSION}} -X main.buildTimeUnix={{.Env.JFA_GO_BUILD_TIME}} -X main.builtBy="{{.Env.JFA_GO_BUILT_BY}}"
    goos:
      - linux
    goarch:
      - arm
      - arm64
      - amd64
snapshot:
  version_template: "0.0.0-{{ .Env.JFA_GO_NFPM_EPOCH }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
